default: &default
  adapter: postgresql
  encoding: unicode
  username: develop
  password: develop
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: depot_development
test:
  <<: *default
  database: depot_test
production:
  <<: *default
  database: depot_production
  username: <%= ENV["DEPOT_DATABASE_USERNAME"] %>
  password: <%= ENV["DEPOT_DATABASE_PASSWORD"] %>
