default: &default
  adapter: postgresql
  encoding: unicode
  username: develop
  password: develop
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: depot_development
test:
  <<: *default
  database: depot_test
production:
  <<: *default
  database: depot_production
  host: db
  username: postgres
  password: password
